name: build
on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'
      - '.gitignore'
    branches-ignore:
      - daily
    tags:
      - '*'
jobs:
  build-ios:
    runs-on: macOS-11.0
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode 13.0
        run: sudo xcode-select --switch /Applications/Xcode_13.0.app/Contents/Developer
      - name: Build WebRTC for iOS
        run: |
          python3 run.py build ios --webrtc-overlap-ios-build-dir
          python3 run.py package ios --webrtc-overlap-ios-build-dir
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: webrtc.ios.tar.gz
          path: _package/ios/webrtc.tar.gz